### ISSUE TITLE
Implement “Well‑formed JSON.stringify”

### ISSUE THREAD

**Issue by ExE-Boss** [ungap/json#2]
See https://github.com/tc39/proposal-well-formed-stringify for specification and reasoning.

**Comment by WebReflection** [comment]
would this be enough as work around?

```js
JSON.stringify(any).replace(/[\uD000-\uDFFF]/g, c => '\\' + escape(c).slice(1))
// or
JSON.stringify(any).replace(/[\uD000-\uDFFF]/g, c => escape(c).replace('%', '\\'))
```

I don't want to bloat this poly with all Unicode rules, pairs and surrogate, so I hope that is what you are looking for

**Comment by WebReflection** [comment]
No answer since august, closing this assuming the workaround worked fine.

**Comment by ExE-Boss** [comment]
I completely forgot about this, but the correct fix is:
```js
const suRe = /(^|.)([\uD800-\uDFFF])(.|$)/g;
const suLow = /^[\uD800-\uDBFF]$/;
const suHi = /^[\uDC00-\uDFFF]$/;
function suFix(re, before, cp, after) {
	if (
		(suLow.test(cp) && !suHi.test(after)) ||
		(suHi.test(cp) && !suLow.test(before))
	) {
		return before + '\\' + escape(cp).slice(1) + after;
	}
	return re;
}

JSON.stringify(any).replace(suRe, suFix);
```

**Comment by WebReflection** [comment]
Do you have any example for the `suHi.test(codePoint) && !suLow.test(before)` case? I' trying to keep the code coverage at same level, thanks.

P.S. yes, I think it's worth providing this fix too, as the needed code doesn't seem too much of an overhead.

**Comment by ExE-Boss** [comment]
The string `"\uDEAD"` does match `high.test(codePoint) && !low.test(before)`.

**Comment by WebReflection** [comment]
Not accordingly to the code coverage

**Comment by zloirock** [comment]
With `'\uDF06\uD834'` the second code point will be ignored.

**Comment by WebReflection** [comment]
I indeed have the feeling the regexp easily misses points due dot, so that I should check just the ranges and find out via index the before/after part.

Thanks for pointing it out

**Comment by zloirock** [comment]
Thanks for the idea https://github.com/zloirock/core-js/pull/681 -)

**Comment by WebReflection** [comment]
Couldn't core just have some micro-dependency when it makes sense? 🤔

Just wondering

**Comment by zloirock** [comment]
At this moment, the `core-js` policy is that the main package should not have any dependencies. In the future - maybe. I'm always happy to see new contributors -)

**Comment by WebReflection** [comment]
> I'm always happy to see new contributors -)

IIRC core is a monolith, for understandable reasons, here pretty much everything is meant to be vaporwhare, but thanks for the explaining the reasoning.

**Comment by WebReflection** [comment]
FYI the version `1.0.0` also fixes not well formed strings.
